POST  http://localhost:3001/create-checkout-session
content-type: application/json

{
    "basket": [
        { 
            "title": "teclado 100% real no fake",
            "id": 2,
            "price": 100,
            "quantity": 1
        },
        
        

    ]
   
}