POST http://localhost:3001/reset-password/3/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvcmdldG9tYXNkYXZhbGlsbG9AZ21haWwuY29tIiwiaWQiOjMsImlhdCI6MTY2Nzk4Nzk3MywiZXhwIjoxNjY3OTg4MjczfQ.S8tE8z6dg4ksiwQHhqh-QRNVF58hWz8qv7J5-yaVlLU
content-type: application/json

{
    "password": "132"
}